### ISSUE TITLE
Android does not use google-services.json the correct way

### ISSUE THREAD

**Issue by mcfarljw** [chemerisuk/cordova-plugin-firebase-hooks#2]
One major problem with this is that it doesn't use `google-services.json` the way it was intended to be used for a several reasons.

**1.) It only pulls the client info and key from the first application.** 

https://github.com/chemerisuk/cordova-plugin-firebase-hooks/blob/master/hooks/android/copy-google-services.js#L55-L59

```
// notice the array is hardcoded to pull from the first index
json.client[0].client_info.mobilesdk_app_id
json.client[0].api_key[0].current_key
```

**2.) The framework gradleReference declaration does nothing.**

https://github.com/chemerisuk/cordova-plugin-firebase-hooks/blob/e2e360f3ae2e8cda2d14744babdec821b9e0e31e/plugin.xml#L30

https://github.com/chemerisuk/cordova-plugin-firebase-hooks/blob/e2e360f3ae2e8cda2d14744babdec821b9e0e31e/src/android/build.gradle#L5-L7

```
// never actually makes it into the cordova gradle build
dependencies {
    classpath 'com.google.gms:google-services:3.0.0'
}
```

**3.) The 1st issue is a hack for the 2nd issue.**

https://developers.google.com/android/guides/google-services-plugin#processing_the_json_file

Since the `google-services` dependency classpath plugin never gets properly applied the hook just manually sets the values in the string xml file. It the dependency was working then it'd be able to parse the json file on it's on and properly set the strings based on the project id.

**Comment by yuriploc** [comment]
@mcfarljw What fix would you suggest?

**Comment by mcfarljw** [comment]
I would go through the Firebase Android setup guide and use hooks to make sure the process matches what they have described. _For example copying the `google-services.json` file into the app directly before build so that it can get parsed naturally by the firebase sdk._

https://firebase.google.com/docs/android/setup

It's still a work in progress and does a bit too much altering of the `build.gradle` file, but here is my attempt at making the firebase sdk work a little more naturally with cordova.

https://github.com/mcfarljw/cordova-plugin-google-services/blob/master/hooks/android.js

**Comment by chemerisuk** [comment]
This plugin is no longer maintained. All cordova firebase plugins are depended on cordova-plugin-firebase-analytics.
