### ISSUE TITLE
Ionic package not working

### ISSUE THREAD

**Issue by MarinoRaul** [chemerisuk/cordova-plugin-firebase-hooks#6]
I got the error of Xcode module not found when I run througth ionic package build ios!

I need to understand which version requires analytics hooks cocoadpod support etc for what I could run successfully in Linux machine!!!

Thanks a lot

**Comment by chemerisuk** [comment]
This plugin is no longer maintained. All cordova firebase plugins are depended on cordova-plugin-firebase-analytics.
